### ISSUE TITLE
API: don't encode description as htmlentities, send back utf8 instead

### ISSUE THREAD

**Issue by mayel** [mayel/LETS-app#16]

**Comment by matslats** [comment]
I'm not encoding the description as htmlentities on the way out but the greek text coming in from the app is being saved as html entities in the db.
So what's really needed is to [decode](http://php.net/manual/en/function.html-entity-decode.php) the php://input?
```
  $input = file_get_contents('php://input');
  $body_array = (array)json_decode($input);
  foreach ($body_array as $key => &$val) {
    $body_array[$key] = html_entity_decode($val);
  }
```
I've implemented this - does it look right to you?

**Comment by mayel** [comment]
That looks ok, but this was noticed on Greek language listings which I assumed created via Drupal rather than the app?

**Comment by matslats** [comment]
Right there are some configuration issues with the Drupal text editor...

**Comment by matslats** [comment]
The problem in drupal 7 is that one filter format returns UTF8 chars and and other returns htmlentities, and I can't find the difference between their settings.
I don't have time to debug this until it is causing problems.
