### ISSUE TITLE
API: Username autocomplete doesn't work

### ISSUE THREAD

**Issue by mayel** [mayel/LETS-app#17]
http://athens.communityforge.net/commex/member?fields=&fragment=m&limit=3 returns an empty array

**Comment by matslats** [comment]
The correct url is
http://athens.communityforge.net/commex/member?fields=name&fragment=m&limit=3
By the way the API should specify that name is a required field on the member entity

**Comment by mayel** [comment]
Right, but the URL used is provided by OPTIONS on http://athens.communityforge.net/commex/transaction
Which currently provides:
`autocomplete: "fields=&fragment="`

**Comment by matslats** [comment]
This is fixed.
