### ISSUE TITLE
Error editing profile 

### ISSUE THREAD

**Issue by mayel** [mayel/LETS-app#18]
Editing profile on AIC, API returns with error (with location fields empty): 
Compound field Coordinates requires an array value, but received NULL

**Comment by mayel** [comment]
I tried putting in numbers in both fields, but got same error.
This was sent in the PATCH:
` "coordinates": [
    "1",
    "2"
  ],`

**Comment by matslats** [comment]
ok I fixed this on athens. Note that not all sites support coordinates, so the field may not appear at all.
