### ISSUE TITLE
I cannot connect to integralces

### ISSUE THREAD

**Issue by pablogrod** [mayel/LETS-app#21]
I have an account in https://www.integralces.net/es/ and cannot connect to it with the app. I get an error message telling "There was a connection or server error. Unexpected token in JSON at position 0" . I can log in to the website using my desktop PC but I can't using my smartphone either.

**Comment by matslats** [comment]
Sorry but the Integral CES platform doesn't support the Commex API which the App uses.
I'll be happy to work with the Integral CES team if they want to support the app.
Should only be about 2 days work.

**Comment by pablogrod** [comment]
Thanks for your answer. I cannot guarantee the participation of IntegralCES team. I am just a user. I am exploring apps and platforms to use a local social currency in our city, and wanted to explore the Commex API usinng an existing account. Maybe I can create a new account at https://www.community-exchange.org/, right?

**Comment by matslats** [comment]
community-exchange.org should support the commex API, but might not be full working. It has an optional adaptive interface at http://mobi.community-exchange.org and you should point the app towards that. Its probably not fully debugged.
Also try http://demo.communityforge.net and http://timeoverflow.org (It is spanish but not commexAPI)

**Comment by pablogrod** [comment]
Thanks for your answer. I cannot guarantee the participation of IntegralCES team. I am just a user. I am exploring apps and platforms to use a local social currency in our city, and wanted to explore the Commex API usinng an existing account. Maybe I can create a new account at https://www.community-exchange.org/, right?

**Comment by pablogrod** [comment]
Pointing the app to at http://mobi.community-exchange.org retrieves the same error message, and login through the mobile is also imposible. Looks that login is not possible from the smartphone. I guess it will be fixed in a next version.

**Comment by matslats** [comment]
I managed to log in by putting the url without the http prefix
mobi.community-exchange.org

**Comment by pablogrod** [comment]
Pointing the app to at http://mobi.community-exchange.org retrieves the same error message, and login through the mobile is also imposible. Looks that login is not possible from the smartphone. I guess it will be fixed in a next version.

**Comment by pablogrod** [comment]
Now I get another error message and still cannot login: "Please check your details. Your login details may be incorrect, please log out and login again". 
I am using the same credentials I use when loggin through the web, but it doesn't seem to work in the app. 
Regarding the mobile website I discovered that can login using regular Firefox browser. It is Firefox Klar wich fails to connect. This browser uses high security and privacy restrictions. I have configured this version as default in my smartphone.  
Hypothesizing that the app may be using the default browser to connect, I tried setting ordinary Firefox as my default browser and retried connection through the app but this didn't fixed the problem.

**Comment by matslats** [comment]
did you try putting http://mobi.community-exchange.org explicitly?
I tested this on mine and it works.
