### ISSUE TITLE
Cannot search terms in Greek

### ISSUE THREAD

**Issue by jsalatas** [mayel/LETS-app#8]
Tried it in athen's site: if you search for an offer in greek you will get not results.

Maybe this a general issue having to do with non-latin charsets as I was also having troubles to login because my username was in greek, when I changed my name in english then I could login without issues.

**Comment by matslats** [comment]
The Drupal database handles multiple languages very well so I would expect non-latiin charsets to work seamlessly, and don't have any idea what is the problem right now.
Languages aren't supported in the app right now. Hopefully in a few weeks we'll get to it.

**Comment by jsalatas** [comment]
In the website search is working ok, so I guess it is some kind of client side encoding problem or something? :\

**Comment by mayel** [comment]
@matslats you may need to decode the fragment parameter on the API end before using it, as it is being URL-encoded

**Comment by matslats** [comment]
I've done a urldecode on the fragment, that might do it.

**Comment by jsalatas** [comment]
Still not solved. I just tried it in athens' site with the latest update from google play.

If you want to test it yourself try searching for Εργασίες in athens' site. It should bring 3 results.

**Comment by mayel** [comment]
Yeah doesn't seem to work on http://athens.communityforge.net/commex/offer?depth=2&offset=0&limit=20&sort=expires,desc&fragment=%CE%95%CF%81%CE%B3%CE%B1%CF%83%CE%AF%CE%B5%CF%82

**Comment by matslats** [comment]
Ok fixed now.
I think it is case insensitive.

**Comment by jsalatas** [comment]
Yeah! It works now! 
But it seems it not case sensitive. I'll post a screenshot in telegram to explain what I mean.
